[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jaseci-website"
version = "0.0.1"
description = "MkDocs-based documentation site for Jaseci."
dependencies = [
    "mkdocs"
]
